In [1]:
import numpy as np

In [2]:
A = np.array([[3, 0],[-1,2],[1,1]])
B = np.array([[-3,-1],[2,1],[4,3]])
C = np.array([[1,2,3],[2,0,1]])
D = np.array([[1],[2],[3]])

In [3]:
print(A + 2 * B)

[[-3 -2]
 [ 3  4]
 [ 9  7]]


In [4]:
print(np.dot(A, C))

[[ 3  6  9]
 [ 3 -2 -1]
 [ 3  2  4]]


In [5]:
print(3 * D)

[[3]
 [6]
 [9]]


In [6]:
print(A)

[[ 3  0]
 [-1  2]
 [ 1  1]]


In [7]:
print(A.shape)

(3, 2)


In [8]:
print(D.shape)

(3, 1)
