In [1]:
import numpy as np

In [2]:
A = np.array([[1,4,7],[2,5,8],[6,3,2]])
B = np.array([[2],[5],[8]])
C = np.array([[-4,9]])
D = np.array([[2,4,8,4],[4,8,3,1],[7,3,0,5]])

print(np.diag(A))
print(A.shape)
print(B.shape)
print(C.shape)
print(D[1,2])
print(D[2,3])
print(A[1,])
print(D[:,2])

[1 5 2]
(3, 3)
(3, 1)
(1, 2)
3
5
[2 5 8]
[8 3 0]


In [3]:
A = np.array([[1,5,4,3,2],[9,7,2,5,0]])
B = np.array([[4,6,2,9,3],[9,7,1,2,4]])

# 합, 차
C = A+B
print(C)
D = A-B
print(B)

# 스칼라곱
print(4*A)
print(A*4)


[[ 5 11  6 12  5]
 [18 14  3  7  4]]
[[4 6 2 9 3]
 [9 7 1 2 4]]
[[ 4 20 16 12  8]
 [36 28  8 20  0]]
[[ 4 20 16 12  8]
 [36 28  8 20  0]]
[[31 21]
 [63 57]]
[[31 21]
 [63 57]]
[[31 21]
 [63 57]]


In [4]:
# 행렬곱
A = np.array([[1,2,3],[4,2,7]])
B = np.array([[4,8],[6,2],[5,3]])

print(A@B)
print(np.matmul(A, B))
print(np.dot(A, B))

[[31 21]
 [63 57]]
[[31 21]
 [63 57]]
[[31 21]
 [63 57]]


In [5]:
# 항등원
A = np.eye(2)
B = np.array([[31, 21],[63, 47]])

print(A@B)
print(np.matmul(A, B))

print(B@A)
print(np.matmul(B, A))

[[31. 21.]
 [63. 47.]]
[[31. 21.]
 [63. 47.]]
[[31. 21.]
 [63. 47.]]
[[31. 21.]
 [63. 47.]]


In [6]:
# 제곱
A = np.array([[1,2],[3,4]])

print(A**2)
print(np.linalg.matrix_power(A, 0))
print(np.linalg.matrix_power(A, 2))
print(np.linalg.matrix_power(A, 3))

[[ 1  4]
 [ 9 16]]
[[1 0]
 [0 1]]
[[ 7 10]
 [15 22]]
[[ 37  54]
 [ 81 118]]


In [7]:
# 가역
A = np.array([[2,-3],[1,7]])
B = np.array([[2,4],[1,-3]])

np.linalg.inv(A)
np.linalg.inv(B)

array([[ 0.3,  0.4],
       [ 0.1, -0.2]])

In [8]:
# 비가역
C = np.array([[2,4],[1,2]])

np.linalg.inv(C)

LinAlgError: Singular matrix

In [9]:
# 전치
A = np.array([[2,4,1],[5,7,2]])

A.transpose()

array([[2, 5],
       [4, 7],
       [1, 2]])

In [10]:
# 블록
A11 = np.eye(2)
A12 = np.zeros((2,2))
A21 = np.array([[6,8],[-7,9]])
A22 = 5 * np.eye(2)

A = np.block([[A11, A12], [A21, A22]])

print(np.linalg.matrix_power(A, 2))
print(np.linalg.matrix_power(A, 3))

[[  1.   0.   0.   0.]
 [  0.   1.   0.   0.]
 [ 36.  48.  25.   0.]
 [-42.  54.   0.  25.]]
[[   1.    0.    0.    0.]
 [   0.    1.    0.    0.]
 [ 186.  248.  125.    0.]
 [-217.  279.    0.  125.]]
